#node:
#  build: ./deploy/node
plugin:
  build: .
  volumes:
    - .:/home/app/current
  command: npm run intTest
  links:
    - postgres:postgres
    - eventstore:eventstore
  environment:
    DEBUG: true
    NODE_ENV: development
    APPLICATION_NAME: Workflows
datacontainer:
  build: ./deploy/datacontainer
postgres:
  image: postgres
  environment:
    - LANG=en_US.UTF-8
    - POSTGRES_PASSWORD=password
  ports:
    - 5432:5432
eventstore:
  build: ./deploy/eventstore
  ports:
    - 2113:2113
    - 1113:1113
  volumes_from:
    - datacontainer

