FROM ubuntu

# Maintainer
MAINTAINER Raif Harik <reharik@gmail.com>

RUN mkdir /data && mkdir /data/mongo && mkdir /data/eventstore && mkdir /data/mongo/db

VOLUME /data/mongo/db
VOLUME /data/eventstore
